### ISSUE TITLE
 Start_Ubuntu

### ISSUE THREAD

**Issue by Ankushkaira17** [SU21-DevOps-Shopcart/shopcarts#10]
AS A  developer
I NEED  Ubuntu 
SO THAT  I can use python using the terminal.

ASSUMPTIONS:

Ubuntu 20.04.02 will execute in the specific container.

ACCEPTANCE CRITERIA:

When I run the command "vagrant ssh" in terminal
Then I get "Welcome to Ubuntu 20.04.02"

**Comment by tobyjaguar** [comment]
please see issue #4
