### ISSUE TITLE
Halting Vagrant

### ISSUE THREAD

**Issue by Ankushkaira17** [SU21-DevOps-Shopcart/shopcarts#11]
AS A developer
I NEED to stop the vagrant 
SO THAT we can save our memory for the smooth functioning of our machine.

ASSUMPTIONS:
Vagrant will be halted, stopping the container to not run continuously

ACCEPTANCE CRITERIA:
GIVEN vagrant started
WHEN "vagrant halt" is executed after getting the job done
THEN it will stop the vagrant from using the computer memory as it will be halted.

**Comment by tobyjaguar** [comment]
This should be included in the vagrant story
