### ISSUE TITLE
Create Read Rest API

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#15]
**As a** user
**I need** be able to see item detail like price and time it was added to shopcart
**So that** I will know the the price and time it was added

**Assumptions:** 
* Be able to know detail of item

**Acceptance Criteria:**
```
Given a shopcart of items
When I want to read detail of the item
Then item's price and time it was added to shopcart should be shown
```

**Comment by Ankushkaira17** [comment]
Read is already defined in the test_route.py.
So I guess I should close this issue.
