### ISSUE TITLE
Create Query Rest API

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#19]
**As a** Developer
**I need** Query functionality
**So that** I can get item information in database

**Assumptions:** 
* Be able to Query information in database

**Acceptance Criteria:**
```
Given a items database
When I want to know attribute of item
Then item's information will be shown
```

**Comment by tobyjaguar** [comment]
I am going to pause this one, as we already have a `get_item()` and am going to implement the `list_all()` first
