### ISSUE TITLE
Vagrantfile

### ISSUE THREAD

**Issue by tobyjaguar** [SU21-DevOps-Shopcart/shopcarts#4]
**As a** Developer 
**I need** a Vagrantfile  
**So that** members of the team can quickly get a development environment running  

**Assumptions:** 
* It should create a focal64 box
* It should forward port 5000
* assign itself ip 192.168.33.10
* install a python 3 environment

**Acceptance Criteria:**
```
Given a successful vagrant up instance
When the command `python --version` is executed in the terminal
Then the python version should be returned
```

**Comment by Ankushkaira17** [comment]
In M1 mac, we need to start the docker from the app and then run the "vagrant up "
to start it. In case the vagrant is not running, because I faced this problem in the starting.
