### ISSUE TITLE
Create a .travis.yml file for CI configuration 

### ISSUE THREAD

**Issue by tobyjaguar** [SU21-DevOps-Shopcart/shopcarts#52]
**As a** developer   
**I need** a configuration file for travis  
**So that** all tests run before any PR is accepted  

**Assumptions:** 
* The .travis.yml file runs all tests every time a push to main or a PR is submitted

**Acceptance Criteria:**
```
Given a feature branch
When a PR is created
Then all tests run and only after successful execution of the tests is the PR accepted
```

**Comment by MiaozhiYu** [comment]
Maybe we should also check the code coverage > 95% here? it can be part of the acceptance criterion
