### ISSUE TITLE
Update Vagrantfile for IBM Cloud CLI

### ISSUE THREAD

**Issue by tobyjaguar** [SU21-DevOps-Shopcart/shopcarts#56]
**As a** developer
**I need** access to the IBM Cloud CLI  
**So that** when I start a development environment, I can access IBM Cloud functions  

**Assumptions:** 
* this should follow the `lab-bluemix-cf` repo

**Acceptance Criteria:**
```
Given a vagrant build
When vagrant comes up
Then the machine should be able to run IBM Cloud commands
```

**Comment by tobyjaguar** [comment]
Where is this implemented @wjin17

**Comment by wjin17** [comment]
Just opened a PR

**Comment by wjin17** [comment]
sorry, thanks!
