### ISSUE TITLE
ibmcloud push

### ISSUE THREAD

**Issue by tobyjaguar** [SU21-DevOps-Shopcart/shopcarts#59]
**As a** developer  
**I need** to be able to deploy the service to IBM Cloud  
**So that** customers can reach the service from the e-commerce site

**Assumptions:** 
* `ibmcloud cf push` can execute from the vagrant machine
* the application successfully deploys to the IBM CLoud

**Acceptance Criteria:**
```
Given the command `ibmcloud push`
When executed
Then the application deploys to the IBM Cloud
```

**Comment by tobyjaguar** [comment]
there isn't really any code change here. I did make a Shopcart API key that allows one to login to ibmcloud to push, which I did successfully change the instances. @MiaozhiYu can you review and close this.

**Comment by MiaozhiYu** [comment]
Sure. @tobyjaguar
