### ISSUE TITLE
Add honcho to requirements.txt

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#60]
**As a** developer  
**I need** honcho command available  
**So that** I can use honcho start  

**Assumptions:** 
* honcho will be add to requirement.txt file

**Acceptance Criteria:**
```
Given requirement.txt file
When developer want to run with honcho
Then just type "honcho start"
```

**Comment by tobyjaguar** [comment]
This is already implemented. Try to confirm.
