### ISSUE TITLE
Create a simple single page UI

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#61]
**As a** User 
**I need** UI on webpage  
**So that** I can interact with the app

**Assumptions:** 
* Single page UI 

**Acceptance Criteria:**
```
Given the application
When user want to interact with the app
Then they can interact through UI
```

**Comment by MiaozhiYu** [comment]
@wjin17 is this ready to be moved to Done?

**Comment by wjin17** [comment]
@MiaozhiYu  Let me add Lianghao's new endpoints to the UI
