### ISSUE TITLE
Create BBD.file and steps.py

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#62]
**As a** developer
**I need** some feature
**So that** I can test RESTful API from outside in

**Assumptions:** 
* BBD .feature file 
* steps.py

**Acceptance Criteria:**
```
Given BBD .feature file and steps.py
When developer want to test RESTful API from outsides
Then he or she can make it
```

**Comment by wjin17** [comment]
Check review, might also have to install python3-selenium as a dependency too
