### ISSUE TITLE
Scenario feature: Read

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#64]
**As a** Developer
**I need** a Read Scenarios feature
**So that** I can confirm the read behavior on the client application executes as expected

**Assumptions:** 
* A Read scenarios feature mocks the retrieval of an item in a shopcart

**Acceptance Criteria:**
```
Given the bdd testing framework behave
When the customer_id and product_id are input, and the search button is clicked
Then the item information with customer_id and product_id will be shown
```

**Comment by LianghaoShu** [comment]
Read did not pass integration test

**Comment by MiaozhiYu** [comment]
@LianghaoShu should be good now. plz feel free to double check
