### ISSUE TITLE
Scenario feature: Action

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#69]
**As a** Developer
**I need** a Checkout Scenarios feature
**So that** I can confirm that the checkout action works as expected on the client application

**Assumptions:** 
* An Action scenarios feature that mocks the checkout behavior on the client application

**Acceptance Criteria:**
```
Given the bdd testing framework behave
When the checkout button is clicked
Then the product(s) checkout field is updated from 0 to 1
```

**Comment by MiaozhiYu** [comment]
@tobyjaguar @wjin17 can somebody review this card? thank you. (I am not familiar with javascript so probably wont be able to review it)

**Comment by LianghaoShu** [comment]
Need modification of code to pass integration test
