### ISSUE TITLE
Use Selenium to conduct UI testing

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#70]
**As a** developer  
**I need** Selenium to conduct UI test
**So that** BDD test interact with web interface only

**Assumptions:** 
* use Selenium to conduct UI testing

**Acceptance Criteria:**
```
Given app and Selenium
When developer wants to test
Then use Selenium to conduct UI testing and service interact with web interface only
```

**Comment by wjin17** [comment]
This is already implemented no? Selenium was added to the vagrantfile when adding the bdd feature files

**Comment by MiaozhiYu** [comment]
@wjin17 @tobyjaguar @LianghaoShu Hey, just want to confirm the status of this card.
