### ISSUE TITLE
ReFactor using Flask-RESTX

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#71]
**As a** developer
**I need** refactor code 
**So that** code wil be from a basic Flask application to one that use Flask-RESTX, and make sure all HTTP error return json error and make sure Flask-RESTX implementation still work

**Assumptions:** 
* Refactor micro service to use Flask-RESTX
* HTTP errors return json
* make sure Flask-RESTX implementation still work

**Acceptance Criteria:**
```
Given App code
When bad data is input into the service
Then 500/400 code should return ...
```

**Comment by MiaozhiYu** [comment]
Acceptance criterion?
```Given App code
When bad data is input into the service
Then 500/400 code should return ...
