### ISSUE TITLE
Set up Devops Continuous Delivery pipeline in IBM cloud

### ISSUE THREAD

**Issue by MiaozhiYu** [SU21-DevOps-Shopcart/shopcarts#75]
---
name: Story
about: Create a User Story to enhance the product
title: ''
labels: enhancement
assignees: ''

---

**As a developer** ...  
**I need to set up the devops continuous pipeline in IBM cloud** ...  
**So that my project can be continuously built and deployed** ...  

**Assumptions:** 
* ...

**Acceptance Criteria:**
```
Given the pipeline...
When ...
Then ...
```

**Comment by LianghaoShu** [comment]
Build, Deploy, Test Stages are all set, Production stage need to be check

**Comment by MiaozhiYu** [comment]
@LianghaoShu looks like the test stage failed. do you need any help on that?

**Comment by LianghaoShu** [comment]
@MiaozhiYu Integration test fail is expected, because we do not have BDD test all set.

**Comment by LianghaoShu** [comment]
Production stage need more configuration. In progress.
