### ISSUE TITLE
Change ReadMe File according to project

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#78]
**As a** user
**I need**  ReadMe file
**So that** I can know how to run the app 

**Assumptions:** 
* Change ReadMe according to changes to code

**Acceptance Criteria:**
```
Given Readme file
When user wants to run the app
Then he or she will understand what is expected by the app and what will be output 
```

**Comment by MiaozhiYu** [comment]
@Ankushkaira17 Hey, may I confirm the status of this card? Thanks!
