### ISSUE TITLE
Issue_template.md

### ISSUE THREAD

**Issue by Ankushkaira17** [SU21-DevOps-Shopcart/shopcarts#9]
As a .....
I need .....
so that .....

Assumptions:
 ...
 Acceptance criteria: 
Given ...
When ...
Then ...

**Comment by tobyjaguar** [comment]
hey @Ankushkaira17 I added the story template. To access it click on the "new issue" button, and there should be a menu for story or bug report.

**Comment by Ankushkaira17** [comment]
I added it so that we can get the format of the story format.
Should I remove this story?

**Comment by tobyjaguar** [comment]
Right, so the template is already done. Can you review the DevOps project specification and add some stories based off of what we need to do for Sprint 1?

**Comment by Ankushkaira17** [comment]
Sure!
