### ISSUE TITLE
Action to change product status

### ISSUE THREAD

**Issue by LianghaoShu** [SU21-DevOps-Shopcart/shopcarts#92]
**As a** shop owner
**I need** change status action 
**So that** I can change product status if product is in order

**Assumptions:** 
* Change product status action

**Acceptance Criteria:**
```
Given product app
When shop owner want to change product status
Then he or she will be able to do that
```

**Comment by LianghaoShu** [comment]
change from in stock to checkout

**Comment by LianghaoShu** [comment]
This might need to add more features about action such as checkout all and checkout multiple. @MiaozhiYu I'll let you know if you can move them to close.

**Comment by MiaozhiYu** [comment]
@LianghaoShu is this ready to be moved to Done?

**Comment by LianghaoShu** [comment]
This is done,can be moved @MiaozhiYu
